### ISSUE TITLE
Make title and description optional, and show it in the public page

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-participatory-documents#25]
Currently, we force the admins to introduce a title and a description when PDF is uploaded:
![image](https://user-images.githubusercontent.com/1401520/207831411-c75b51e3-78d5-443f-a462-f441f1b22088.png)

- [x] Make title and description optionall
- [x] Show in the public page the title and the description if they exists only.
- [x] Add to the `div.row` containing the iframe with the PDF rendering a minimal height through a class, css could be:
  ```css
  .pdf-viewer-container {
    height: calc(100vh - 30rem);
    min-height: 50em;
    margin: 0;
    padding: 0;
  }
  ```
- [x] Add tests

Mockup:

![Screenshot from 2022-12-15 11-10-52](https://user-images.githubusercontent.com/1401520/207833111-c11591e1-b6b5-4358-9c89-c41a37be6294.png)
